### ISSUE TITLE
Option to specify channel events for route

### ISSUE THREAD

**Issue by mubarak** [sinetja/netty-router#10]
It appears from [1] that routed handler always gets `channelRead` and then `channelRead0`, if i need to do some state management when channel is active in `channelActive` (e.g: proxy: [2]) then `channelActive` never gets called as channel event. I think the workaround is to call `ctx.fireChannelActive` before `ctx.fireChannelRead(routed)` in [1]. If routed handler overrides any of channel events from `ChannelInboundHandlerAdapter (channelRegistered, channelReadComplete)` etc then overriden methods won't be called.

[1] https://github.com/sinetja/netty-router/blob/revert-9-netty41/src/main/java/io/netty/handler/codec/http/router/Handler.java#L62

[2] https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/proxy/HexDumpProxyFrontendHandler.java#L40

**Comment by ngocdaothanh** [comment]
About channelActive event:

As explained in README, when a request comes in, netty-router dynamically adds your matched handler behind itself, then passes Routed object to your handler. At this time, channelActive event should already happened, because the channel already received a request.

Maybe you want to do the state management when your handler is constructed or added to the channel pipeline:
http://netty.io/4.0/api/io/netty/channel/ChannelHandler.html

Alternatively, you may override the router handler itself. This is used in the web framework Sinetja, 
https://github.com/sinetja/sinetja/blob/master/src/main/java/sinetja/RouterHandler.java

**Comment by mubarak** [comment]
Thanks. I will try and let you know.
